// <auto-generated />
using System;
using HatirlaticiAPI.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HatirlaticiAPI.Persistence.Migrations
{
    [DbContext(typeof(HatirlaticiDbContext))]
    partial class HatirlaticiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TbFiles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TbFile");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbGroups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TbReminderId")
                        .HasColumnType("int");

                    b.Property<int?>("TbUsersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TbReminderId");

                    b.HasIndex("TbUsersId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TbUsersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TbUsersId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBrith")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.GroupImageFile", b =>
                {
                    b.HasBaseType("HatirlaticiAPI.Domain.Entities.TbFile");

                    b.HasDiscriminator().HasValue("GroupImageFile");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.UserImageFile", b =>
                {
                    b.HasBaseType("HatirlaticiAPI.Domain.Entities.TbFile");

                    b.HasDiscriminator().HasValue("UserImageFile");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbGroups", b =>
                {
                    b.HasOne("HatirlaticiAPI.Domain.Entities.TbReminder", null)
                        .WithMany("Groups")
                        .HasForeignKey("TbReminderId");

                    b.HasOne("HatirlaticiAPI.Domain.Entities.TbUsers", null)
                        .WithMany("Groups")
                        .HasForeignKey("TbUsersId");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbReminder", b =>
                {
                    b.HasOne("HatirlaticiAPI.Domain.Entities.TbUsers", null)
                        .WithMany("Reminders")
                        .HasForeignKey("TbUsersId");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbReminder", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("HatirlaticiAPI.Domain.Entities.TbUsers", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
